# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  database: development
  username:  root
  password:
  host: localhost

development_master:
  adapter: mysql2
  database: development_master
  username:  root
  password:
  host: localhost
  
development_slave:
  adapter: mysql2
  database: development_slave
  username:  root
  password:
  host: localhost
  check_interval: 2
  delay_threshold: 3
  